/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Ajouter_un_agent (void)
{
  GtkWidget *Ajouter_un_agent;
  GtkWidget *fixed3;
  GtkWidget *prenom;
  GtkWidget *email;
  GtkWidget *numTEL;
  GtkWidget *ville;
  GtkWidget *CIN;
  GtkWidget *label25;
  GtkWidget *label17;
  GtkWidget *label23;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label24;
  GtkObject *datedenaissancejour_adj;
  GtkWidget *datedenaissancejour;
  GtkWidget *button16;
  GtkWidget *alignment1;
  GtkWidget *nom;
  GtkWidget *label22;
  GtkObject *datederecrutementjour_adj;
  GtkWidget *datederecrutementjour;
  GtkWidget *label15;
  GtkWidget *label21;
  GtkWidget *label97;
  GtkObject *datedenaissancemois_adj;
  GtkWidget *datedenaissancemois;
  GtkObject *datedenaissanceannee_adj;
  GtkWidget *datedenaissanceannee;
  GtkObject *datederecrutementmois_adj;
  GtkWidget *datederecrutementmois;
  GtkObject *datederecrutementannee_adj;
  GtkWidget *datederecrutementannee;
  GtkWidget *ajouter;
  GtkWidget *label20;
  GtkWidget *label14;
  GtkWidget *homme;
  GSList *homme_group = NULL;
  GtkWidget *femme;
  GtkWidget *output;
  GtkWidget *poste_de_travail;
  GtkWidget *horraires_de_travail;

  Ajouter_un_agent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajouter_un_agent), _("window ajouter"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Ajouter_un_agent), fixed3);

  prenom = gtk_entry_new ();
  gtk_widget_show (prenom);
  gtk_fixed_put (GTK_FIXED (fixed3), prenom, 180, 100);
  gtk_widget_set_size_request (prenom, 208, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenom), 8226);

  email = gtk_entry_new ();
  gtk_widget_show (email);
  gtk_fixed_put (GTK_FIXED (fixed3), email, 180, 400);
  gtk_widget_set_size_request (email, 208, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (email), 8226);

  numTEL = gtk_entry_new ();
  gtk_widget_show (numTEL);
  gtk_fixed_put (GTK_FIXED (fixed3), numTEL, 180, 352);
  gtk_widget_set_size_request (numTEL, 208, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (numTEL), 8226);

  ville = gtk_entry_new ();
  gtk_widget_show (ville);
  gtk_fixed_put (GTK_FIXED (fixed3), ville, 180, 300);
  gtk_widget_set_size_request (ville, 208, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (ville), 8226);

  CIN = gtk_entry_new ();
  gtk_widget_show (CIN);
  gtk_fixed_put (GTK_FIXED (fixed3), CIN, 180, 152);
  gtk_widget_set_size_request (CIN, 208, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (CIN), 8226);

  label25 = gtk_label_new (_("Poste de travail  : "));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed3), label25, 16, 550);
  gtk_widget_set_size_request (label25, 152, 40);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);

  label17 = gtk_label_new (_("e-mail  : "));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 16, 400);
  gtk_widget_set_size_request (label17, 152, 40);
  gtk_misc_set_alignment (GTK_MISC (label17), 0, 0.5);

  label23 = gtk_label_new (_("N\302\260TEL  : "));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed3), label23, 16, 350);
  gtk_widget_set_size_request (label23, 152, 40);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0.5);

  label18 = gtk_label_new (_("Ville actuelle : "));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 16, 300);
  gtk_widget_set_size_request (label18, 152, 40);
  gtk_misc_set_alignment (GTK_MISC (label18), 0, 0.5);

  label19 = gtk_label_new (_("sexe : "));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed3), label19, 16, 250);
  gtk_widget_set_size_request (label19, 152, 40);
  gtk_misc_set_alignment (GTK_MISC (label19), 0, 0.5);

  label24 = gtk_label_new (_("Date de recrutement  : "));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed3), label24, 16, 450);
  gtk_widget_set_size_request (label24, 152, 40);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0.5);

  datedenaissancejour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  datedenaissancejour = gtk_spin_button_new (GTK_ADJUSTMENT (datedenaissancejour_adj), 1, 0);
  gtk_widget_show (datedenaissancejour);
  gtk_fixed_put (GTK_FIXED (fixed3), datedenaissancejour, 180, 200);
  gtk_widget_set_size_request (datedenaissancejour, 60, 28);

  button16 = gtk_button_new_with_mnemonic (_("X"));
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed3), button16, 488, 8);
  gtk_widget_set_size_request (button16, 40, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_fixed_put (GTK_FIXED (fixed3), alignment1, 184, 48);
  gtk_widget_set_size_request (alignment1, 208, 40);

  nom = gtk_entry_new ();
  gtk_widget_show (nom);
  gtk_container_add (GTK_CONTAINER (alignment1), nom);
  gtk_widget_set_size_request (nom, 208, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom), 8226);

  label22 = gtk_label_new (_("Horraires de travail  : "));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed3), label22, 16, 500);
  gtk_widget_set_size_request (label22, 152, 40);
  gtk_misc_set_alignment (GTK_MISC (label22), 0, 0.5);

  datederecrutementjour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  datederecrutementjour = gtk_spin_button_new (GTK_ADJUSTMENT (datederecrutementjour_adj), 1, 0);
  gtk_widget_show (datederecrutementjour);
  gtk_fixed_put (GTK_FIXED (fixed3), datederecrutementjour, 176, 456);
  gtk_widget_set_size_request (datederecrutementjour, 56, 30);

  label15 = gtk_label_new (_("Pr\303\251nom : "));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 16, 100);
  gtk_widget_set_size_request (label15, 152, 40);
  gtk_misc_set_alignment (GTK_MISC (label15), 0, 0.5);

  label21 = gtk_label_new (_("CIN : "));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed3), label21, 16, 150);
  gtk_widget_set_size_request (label21, 152, 40);
  gtk_misc_set_alignment (GTK_MISC (label21), 0, 0.5);

  label97 = gtk_label_new (_("Date de naissance  : "));
  gtk_widget_show (label97);
  gtk_fixed_put (GTK_FIXED (fixed3), label97, 16, 200);
  gtk_widget_set_size_request (label97, 152, 40);
  gtk_misc_set_alignment (GTK_MISC (label97), 0, 0.5);

  datedenaissancemois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  datedenaissancemois = gtk_spin_button_new (GTK_ADJUSTMENT (datedenaissancemois_adj), 1, 0);
  gtk_widget_show (datedenaissancemois);
  gtk_fixed_put (GTK_FIXED (fixed3), datedenaissancemois, 256, 200);
  gtk_widget_set_size_request (datedenaissancemois, 60, 28);

  datedenaissanceannee_adj = gtk_adjustment_new (1, 2000, 2024, 1, 10, 10);
  datedenaissanceannee = gtk_spin_button_new (GTK_ADJUSTMENT (datedenaissanceannee_adj), 1, 0);
  gtk_widget_show (datedenaissanceannee);
  gtk_fixed_put (GTK_FIXED (fixed3), datedenaissanceannee, 344, 200);
  gtk_widget_set_size_request (datedenaissanceannee, 120, 28);

  datederecrutementmois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  datederecrutementmois = gtk_spin_button_new (GTK_ADJUSTMENT (datederecrutementmois_adj), 1, 0);
  gtk_widget_show (datederecrutementmois);
  gtk_fixed_put (GTK_FIXED (fixed3), datederecrutementmois, 256, 456);
  gtk_widget_set_size_request (datederecrutementmois, 56, 30);

  datederecrutementannee_adj = gtk_adjustment_new (1, 2000, 2024, 1, 10, 10);
  datederecrutementannee = gtk_spin_button_new (GTK_ADJUSTMENT (datederecrutementannee_adj), 1, 0);
  gtk_widget_show (datederecrutementannee);
  gtk_fixed_put (GTK_FIXED (fixed3), datederecrutementannee, 328, 456);
  gtk_widget_set_size_request (datederecrutementannee, 120, 32);

  ajouter = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed3), ajouter, 408, 592);
  gtk_widget_set_size_request (ajouter, 128, 60);

  label20 = gtk_label_new (_("Nom : "));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed3), label20, 16, 50);
  gtk_widget_set_size_request (label20, 149, 40);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);

  label14 = gtk_label_new (_("Ajouter un agent"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed3), label14, 111, 8);
  gtk_widget_set_size_request (label14, 289, 32);

  homme = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (homme);
  gtk_fixed_put (GTK_FIXED (fixed3), homme, 180, 250);
  gtk_widget_set_size_request (homme, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (homme), homme_group);
  homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (homme));

  femme = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (femme);
  gtk_fixed_put (GTK_FIXED (fixed3), femme, 320, 250);
  gtk_widget_set_size_request (femme, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (femme), homme_group);
  homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (femme));

  output = gtk_label_new ("");
  gtk_widget_show (output);
  gtk_fixed_put (GTK_FIXED (fixed3), output, 24, 624);
  gtk_widget_set_size_request (output, 328, 33);

  poste_de_travail = gtk_combo_box_entry_new_text ();
  gtk_widget_show (poste_de_travail);
  gtk_fixed_put (GTK_FIXED (fixed3), poste_de_travail, 184, 550);
  gtk_widget_set_size_request (poste_de_travail, 208, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (poste_de_travail), _("Poste1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (poste_de_travail), _("Poste2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (poste_de_travail), _("Poste3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (poste_de_travail), _("Poste4"));

  horraires_de_travail = gtk_combo_box_entry_new_text ();
  gtk_widget_show (horraires_de_travail);
  gtk_fixed_put (GTK_FIXED (fixed3), horraires_de_travail, 184, 500);
  gtk_widget_set_size_request (horraires_de_travail, 208, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (horraires_de_travail), _("8h==>16h"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (horraires_de_travail), _("16h==>00h"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (horraires_de_travail), _("00==>8h"));

  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajouter_un_agent, Ajouter_un_agent, "Ajouter_un_agent");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, prenom, "prenom");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, email, "email");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, numTEL, "numTEL");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, ville, "ville");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, CIN, "CIN");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, label25, "label25");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, label17, "label17");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, label23, "label23");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, label18, "label18");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, label19, "label19");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, label24, "label24");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, datedenaissancejour, "datedenaissancejour");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, button16, "button16");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, nom, "nom");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, label22, "label22");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, datederecrutementjour, "datederecrutementjour");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, label15, "label15");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, label21, "label21");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, label97, "label97");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, datedenaissancemois, "datedenaissancemois");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, datedenaissanceannee, "datedenaissanceannee");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, datederecrutementmois, "datederecrutementmois");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, datederecrutementannee, "datederecrutementannee");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, label20, "label20");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, label14, "label14");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, homme, "homme");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, femme, "femme");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, output, "output");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, poste_de_travail, "poste_de_travail");
  GLADE_HOOKUP_OBJECT (Ajouter_un_agent, horraires_de_travail, "horraires_de_travail");

  return Ajouter_un_agent;
}

GtkWidget*
create_connexion_admin (void)
{
  GtkWidget *connexion_admin;
  GtkWidget *fixed2;
  GtkWidget *ayoub_connexion_admin_text_CIN_admin;
  GtkWidget *ayoub_connexion_admin_text_mot_de_passe;
  GtkWidget *label28;
  GtkWidget *label27;
  GtkWidget *ayoub_connexion_admin_button_se_connecter;
  GtkWidget *label26;

  connexion_admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (connexion_admin), _("window2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (connexion_admin), fixed2);

  ayoub_connexion_admin_text_CIN_admin = gtk_entry_new ();
  gtk_widget_show (ayoub_connexion_admin_text_CIN_admin);
  gtk_fixed_put (GTK_FIXED (fixed2), ayoub_connexion_admin_text_CIN_admin, 152, 56);
  gtk_widget_set_size_request (ayoub_connexion_admin_text_CIN_admin, 190, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (ayoub_connexion_admin_text_CIN_admin), 8226);

  ayoub_connexion_admin_text_mot_de_passe = gtk_entry_new ();
  gtk_widget_show (ayoub_connexion_admin_text_mot_de_passe);
  gtk_fixed_put (GTK_FIXED (fixed2), ayoub_connexion_admin_text_mot_de_passe, 152, 120);
  gtk_widget_set_size_request (ayoub_connexion_admin_text_mot_de_passe, 190, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (ayoub_connexion_admin_text_mot_de_passe), 8226);

  label28 = gtk_label_new (_("Mot de passe\t : "));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed2), label28, 16, 120);
  gtk_widget_set_size_request (label28, 120, 40);
  gtk_misc_set_alignment (GTK_MISC (label28), 0, 0.5);

  label27 = gtk_label_new (_("CIN admin : "));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed2), label27, 16, 60);
  gtk_widget_set_size_request (label27, 100, 40);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);

  ayoub_connexion_admin_button_se_connecter = gtk_button_new_with_mnemonic (_("Se connecter"));
  gtk_widget_show (ayoub_connexion_admin_button_se_connecter);
  gtk_fixed_put (GTK_FIXED (fixed2), ayoub_connexion_admin_button_se_connecter, 256, 176);
  gtk_widget_set_size_request (ayoub_connexion_admin_button_se_connecter, 130, 40);

  label26 = gtk_label_new (_("Connexion admin"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed2), label26, 56, 8);
  gtk_widget_set_size_request (label26, 240, 47);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (connexion_admin, connexion_admin, "connexion_admin");
  GLADE_HOOKUP_OBJECT (connexion_admin, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (connexion_admin, ayoub_connexion_admin_text_CIN_admin, "ayoub_connexion_admin_text_CIN_admin");
  GLADE_HOOKUP_OBJECT (connexion_admin, ayoub_connexion_admin_text_mot_de_passe, "ayoub_connexion_admin_text_mot_de_passe");
  GLADE_HOOKUP_OBJECT (connexion_admin, label28, "label28");
  GLADE_HOOKUP_OBJECT (connexion_admin, label27, "label27");
  GLADE_HOOKUP_OBJECT (connexion_admin, ayoub_connexion_admin_button_se_connecter, "ayoub_connexion_admin_button_se_connecter");
  GLADE_HOOKUP_OBJECT (connexion_admin, label26, "label26");

  return connexion_admin;
}

GtkWidget*
create_Erreur_de_connexion_admin (void)
{
  GtkWidget *Erreur_de_connexion_admin;
  GtkWidget *fixed4;
  GtkWidget *label29;
  GtkWidget *ayoub_erreur_connexion_admin_button_OK;

  Erreur_de_connexion_admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Erreur_de_connexion_admin), _("window3"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Erreur_de_connexion_admin), fixed4);

  label29 = gtk_label_new (_("Impossible de se connecter !\nCIN de l'administrateur ou le mot de passe que vous avez saisi est incorrecte. veuillez r\303\251essayer."));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed4), label29, 48, 24);
  gtk_widget_set_size_request (label29, 792, 96);

  ayoub_erreur_connexion_admin_button_OK = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (ayoub_erreur_connexion_admin_button_OK);
  gtk_fixed_put (GTK_FIXED (fixed4), ayoub_erreur_connexion_admin_button_OK, 360, 112);
  gtk_widget_set_size_request (ayoub_erreur_connexion_admin_button_OK, 104, 56);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Erreur_de_connexion_admin, Erreur_de_connexion_admin, "Erreur_de_connexion_admin");
  GLADE_HOOKUP_OBJECT (Erreur_de_connexion_admin, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Erreur_de_connexion_admin, label29, "label29");
  GLADE_HOOKUP_OBJECT (Erreur_de_connexion_admin, ayoub_erreur_connexion_admin_button_OK, "ayoub_erreur_connexion_admin_button_OK");

  return Erreur_de_connexion_admin;
}

GtkWidget*
create_Supprimer_un_agent (void)
{
  GtkWidget *Supprimer_un_agent;
  GtkWidget *fixed5;
  GtkWidget *CIN;
  GtkWidget *button28;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *output;
  GtkWidget *continuer;

  Supprimer_un_agent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Supprimer_un_agent), _("Window Supprimer"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Supprimer_un_agent), fixed5);

  CIN = gtk_entry_new ();
  gtk_widget_show (CIN);
  gtk_fixed_put (GTK_FIXED (fixed5), CIN, 160, 72);
  gtk_widget_set_size_request (CIN, 190, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (CIN), 8226);

  button28 = gtk_button_new_with_mnemonic (_("X"));
  gtk_widget_show (button28);
  gtk_fixed_put (GTK_FIXED (fixed5), button28, 352, 8);
  gtk_widget_set_size_request (button28, 40, 40);

  label30 = gtk_label_new (_("Supprimer un agent de parking \n"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed5), label30, 48, 16);
  gtk_widget_set_size_request (label30, 299, 41);

  label31 = gtk_label_new (_("CIN agent  : "));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed5), label31, 16, 70);
  gtk_widget_set_size_request (label31, 100, 40);
  gtk_misc_set_alignment (GTK_MISC (label31), 0, 0.5);

  output = gtk_label_new ("");
  gtk_widget_show (output);
  gtk_fixed_put (GTK_FIXED (fixed5), output, 32, 176);
  gtk_widget_set_size_request (output, 360, 40);

  continuer = gtk_button_new_with_mnemonic (_("Continuer"));
  gtk_widget_show (continuer);
  gtk_fixed_put (GTK_FIXED (fixed5), continuer, 120, 128);
  gtk_widget_set_size_request (continuer, 130, 40);

  g_signal_connect ((gpointer) continuer, "clicked",
                    G_CALLBACK (on_continuer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Supprimer_un_agent, Supprimer_un_agent, "Supprimer_un_agent");
  GLADE_HOOKUP_OBJECT (Supprimer_un_agent, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Supprimer_un_agent, CIN, "CIN");
  GLADE_HOOKUP_OBJECT (Supprimer_un_agent, button28, "button28");
  GLADE_HOOKUP_OBJECT (Supprimer_un_agent, label30, "label30");
  GLADE_HOOKUP_OBJECT (Supprimer_un_agent, label31, "label31");
  GLADE_HOOKUP_OBJECT (Supprimer_un_agent, output, "output");
  GLADE_HOOKUP_OBJECT (Supprimer_un_agent, continuer, "continuer");

  return Supprimer_un_agent;
}

GtkWidget*
create_agent_introuvable (void)
{
  GtkWidget *agent_introuvable;
  GtkWidget *fixed6;
  GtkWidget *label34;
  GtkWidget *ayoub_agent_introuvable_button_OK;

  agent_introuvable = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (agent_introuvable), _("window5"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (agent_introuvable), fixed6);

  label34 = gtk_label_new (_("                                                   Agent introuvable !\nCIN de l'agent que vous avez saisi est incorrecte. veuillez r\303\251essayer."));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed6), label34, 48, 24);
  gtk_widget_set_size_request (label34, 792, 96);

  ayoub_agent_introuvable_button_OK = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (ayoub_agent_introuvable_button_OK);
  gtk_fixed_put (GTK_FIXED (fixed6), ayoub_agent_introuvable_button_OK, 392, 112);
  gtk_widget_set_size_request (ayoub_agent_introuvable_button_OK, 104, 56);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (agent_introuvable, agent_introuvable, "agent_introuvable");
  GLADE_HOOKUP_OBJECT (agent_introuvable, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (agent_introuvable, label34, "label34");
  GLADE_HOOKUP_OBJECT (agent_introuvable, ayoub_agent_introuvable_button_OK, "ayoub_agent_introuvable_button_OK");

  return agent_introuvable;
}

GtkWidget*
create_mis____jour_compte_agent (void)
{
  GtkWidget *mis____jour_compte_agent;
  GtkWidget *fixed23;
  GtkWidget *label101;
  GtkWidget *label100;
  GtkWidget *label104;
  GtkWidget *label102;
  GtkWidget *label99;
  GtkWidget *email;
  GtkWidget *ville;
  GtkWidget *CIN;
  GtkWidget *prenom;
  GtkWidget *nom;
  GtkWidget *label105;
  GtkWidget *label103;
  GtkWidget *label106;
  GtkWidget *label98;
  GtkWidget *button49;
  GtkWidget *numTEL;
  GtkWidget *output;
  GtkWidget *modifier;
  GtkWidget *horraires;
  GtkWidget *poste;

  mis____jour_compte_agent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (mis____jour_compte_agent), _("window Mis \303\240 jour compte agent"));

  fixed23 = gtk_fixed_new ();
  gtk_widget_show (fixed23);
  gtk_container_add (GTK_CONTAINER (mis____jour_compte_agent), fixed23);

  label101 = gtk_label_new (_("CIN : "));
  gtk_widget_show (label101);
  gtk_fixed_put (GTK_FIXED (fixed23), label101, 30, 160);
  gtk_widget_set_size_request (label101, 130, 40);
  gtk_misc_set_alignment (GTK_MISC (label101), 0, 0.5);

  label100 = gtk_label_new (_("Ville : "));
  gtk_widget_show (label100);
  gtk_fixed_put (GTK_FIXED (fixed23), label100, 30, 210);
  gtk_widget_set_size_request (label100, 130, 40);
  gtk_misc_set_alignment (GTK_MISC (label100), 0, 0.5);

  label104 = gtk_label_new (_("N\302\260 TEL : "));
  gtk_widget_show (label104);
  gtk_fixed_put (GTK_FIXED (fixed23), label104, 30, 260);
  gtk_widget_set_size_request (label104, 130, 40);
  gtk_misc_set_alignment (GTK_MISC (label104), 0, 0.5);

  label102 = gtk_label_new (_("Pr\303\251nom : "));
  gtk_widget_show (label102);
  gtk_fixed_put (GTK_FIXED (fixed23), label102, 30, 110);
  gtk_widget_set_size_request (label102, 130, 40);
  gtk_misc_set_alignment (GTK_MISC (label102), 0, 0.5);

  label99 = gtk_label_new (_("Nom : "));
  gtk_widget_show (label99);
  gtk_fixed_put (GTK_FIXED (fixed23), label99, 30, 60);
  gtk_widget_set_size_request (label99, 130, 40);
  gtk_misc_set_alignment (GTK_MISC (label99), 0, 0.5);

  email = gtk_entry_new ();
  gtk_widget_show (email);
  gtk_fixed_put (GTK_FIXED (fixed23), email, 180, 310);
  gtk_widget_set_size_request (email, 170, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (email), 8226);

  ville = gtk_entry_new ();
  gtk_widget_show (ville);
  gtk_fixed_put (GTK_FIXED (fixed23), ville, 180, 210);
  gtk_widget_set_size_request (ville, 170, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (ville), 8226);

  CIN = gtk_entry_new ();
  gtk_widget_show (CIN);
  gtk_fixed_put (GTK_FIXED (fixed23), CIN, 180, 160);
  gtk_widget_set_size_request (CIN, 170, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (CIN), 8226);

  prenom = gtk_entry_new ();
  gtk_widget_show (prenom);
  gtk_fixed_put (GTK_FIXED (fixed23), prenom, 180, 110);
  gtk_widget_set_size_request (prenom, 170, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenom), 8226);

  nom = gtk_entry_new ();
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed23), nom, 180, 60);
  gtk_widget_set_size_request (nom, 170, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom), 8226);

  label105 = gtk_label_new (_("Poste de travail : "));
  gtk_widget_show (label105);
  gtk_fixed_put (GTK_FIXED (fixed23), label105, 30, 410);
  gtk_widget_set_size_request (label105, 130, 40);
  gtk_misc_set_alignment (GTK_MISC (label105), 0, 0.5);

  label103 = gtk_label_new (_("e-mail : "));
  gtk_widget_show (label103);
  gtk_fixed_put (GTK_FIXED (fixed23), label103, 30, 310);
  gtk_widget_set_size_request (label103, 130, 40);
  gtk_misc_set_alignment (GTK_MISC (label103), 0, 0.5);

  label106 = gtk_label_new (_("Horraires de travail : "));
  gtk_widget_show (label106);
  gtk_fixed_put (GTK_FIXED (fixed23), label106, 30, 360);
  gtk_widget_set_size_request (label106, 141, 40);
  gtk_misc_set_alignment (GTK_MISC (label106), 0, 0.5);

  label98 = gtk_label_new (_("Mis \303\240 jour compte agent de parking\n"));
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixed23), label98, 0, 8);
  gtk_widget_set_size_request (label98, 311, 38);

  button49 = gtk_button_new_with_mnemonic (_("X"));
  gtk_widget_show (button49);
  gtk_fixed_put (GTK_FIXED (fixed23), button49, 328, 0);
  gtk_widget_set_size_request (button49, 40, 40);

  numTEL = gtk_entry_new ();
  gtk_widget_show (numTEL);
  gtk_fixed_put (GTK_FIXED (fixed23), numTEL, 184, 256);
  gtk_widget_set_size_request (numTEL, 170, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (numTEL), 8226);

  output = gtk_label_new ("");
  gtk_widget_show (output);
  gtk_fixed_put (GTK_FIXED (fixed23), output, 32, 544);
  gtk_widget_set_size_request (output, 288, 49);

  modifier = gtk_button_new_with_mnemonic (_("Modifier\n"));
  gtk_widget_show (modifier);
  gtk_fixed_put (GTK_FIXED (fixed23), modifier, 128, 472);
  gtk_widget_set_size_request (modifier, 112, 56);

  horraires = gtk_combo_box_entry_new_text ();
  gtk_widget_show (horraires);
  gtk_fixed_put (GTK_FIXED (fixed23), horraires, 184, 360);
  gtk_widget_set_size_request (horraires, 190, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (horraires), _("8h==>16h"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (horraires), _("16h==>00h"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (horraires), _("00==>8h"));

  poste = gtk_combo_box_entry_new_text ();
  gtk_widget_show (poste);
  gtk_fixed_put (GTK_FIXED (fixed23), poste, 184, 410);
  gtk_widget_set_size_request (poste, 190, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (poste), _("Poste1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (poste), _("Poste2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (poste), _("Poste3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (poste), _("Poste4"));

  g_signal_connect ((gpointer) modifier, "clicked",
                    G_CALLBACK (on_modifier_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mis____jour_compte_agent, mis____jour_compte_agent, "mis____jour_compte_agent");
  GLADE_HOOKUP_OBJECT (mis____jour_compte_agent, fixed23, "fixed23");
  GLADE_HOOKUP_OBJECT (mis____jour_compte_agent, label101, "label101");
  GLADE_HOOKUP_OBJECT (mis____jour_compte_agent, label100, "label100");
  GLADE_HOOKUP_OBJECT (mis____jour_compte_agent, label104, "label104");
  GLADE_HOOKUP_OBJECT (mis____jour_compte_agent, label102, "label102");
  GLADE_HOOKUP_OBJECT (mis____jour_compte_agent, label99, "label99");
  GLADE_HOOKUP_OBJECT (mis____jour_compte_agent, email, "email");
  GLADE_HOOKUP_OBJECT (mis____jour_compte_agent, ville, "ville");
  GLADE_HOOKUP_OBJECT (mis____jour_compte_agent, CIN, "CIN");
  GLADE_HOOKUP_OBJECT (mis____jour_compte_agent, prenom, "prenom");
  GLADE_HOOKUP_OBJECT (mis____jour_compte_agent, nom, "nom");
  GLADE_HOOKUP_OBJECT (mis____jour_compte_agent, label105, "label105");
  GLADE_HOOKUP_OBJECT (mis____jour_compte_agent, label103, "label103");
  GLADE_HOOKUP_OBJECT (mis____jour_compte_agent, label106, "label106");
  GLADE_HOOKUP_OBJECT (mis____jour_compte_agent, label98, "label98");
  GLADE_HOOKUP_OBJECT (mis____jour_compte_agent, button49, "button49");
  GLADE_HOOKUP_OBJECT (mis____jour_compte_agent, numTEL, "numTEL");
  GLADE_HOOKUP_OBJECT (mis____jour_compte_agent, output, "output");
  GLADE_HOOKUP_OBJECT (mis____jour_compte_agent, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (mis____jour_compte_agent, horraires, "horraires");
  GLADE_HOOKUP_OBJECT (mis____jour_compte_agent, poste, "poste");

  return mis____jour_compte_agent;
}

GtkWidget*
create_labelprincipale (void)
{
  GtkWidget *labelprincipale;
  GtkWidget *fixed9;
  GtkWidget *treeview1;
  GtkWidget *supprimer;
  GtkWidget *modifier;
  GtkWidget *ajouter;
  GtkWidget *listereservation;
  GtkWidget *label75;

  labelprincipale = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (labelprincipale), _("window Menu"));
  gtk_window_set_default_size (GTK_WINDOW (labelprincipale), 1666, 1111);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (labelprincipale), fixed9);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed9), treeview1, 279, 40);
  gtk_widget_set_size_request (treeview1, 1029, 440);

  supprimer = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (supprimer);
  gtk_fixed_put (GTK_FIXED (fixed9), supprimer, 760, 520);
  gtk_widget_set_size_request (supprimer, 150, 63);

  modifier = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (modifier);
  gtk_fixed_put (GTK_FIXED (fixed9), modifier, 584, 520);
  gtk_widget_set_size_request (modifier, 150, 63);

  ajouter = gtk_button_new_from_stock ("gtk-add");
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed9), ajouter, 400, 520);
  gtk_widget_set_size_request (ajouter, 150, 63);

  listereservation = gtk_button_new_with_mnemonic (_("Liste des r\303\251servations"));
  gtk_widget_show (listereservation);
  gtk_fixed_put (GTK_FIXED (fixed9), listereservation, 536, 600);
  gtk_widget_set_size_request (listereservation, 215, 63);

  label75 = gtk_label_new (_("Liste des agents :"));
  gtk_widget_show (label75);
  gtk_fixed_put (GTK_FIXED (fixed9), label75, 608, 0);
  gtk_widget_set_size_request (label75, 200, 40);
  gtk_misc_set_alignment (GTK_MISC (label75), 0, 0.5);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) supprimer, "clicked",
                    G_CALLBACK (on_supprimerlabprincipale_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier, "clicked",
                    G_CALLBACK (on_modifierlabprincipale_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouterlabprincipale_clicked),
                    NULL);
  g_signal_connect ((gpointer) listereservation, "clicked",
                    G_CALLBACK (on_listereservation_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (labelprincipale, labelprincipale, "labelprincipale");
  GLADE_HOOKUP_OBJECT (labelprincipale, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (labelprincipale, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (labelprincipale, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (labelprincipale, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (labelprincipale, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (labelprincipale, listereservation, "listereservation");
  GLADE_HOOKUP_OBJECT (labelprincipale, label75, "label75");

  return labelprincipale;
}

GtkWidget*
create___tes_vous_sur_de_vouloir__supprimer_l_agent_de_la_liste___ (void)
{
  GtkWidget *__tes_vous_sur_de_vouloir__supprimer_l_agent_de_la_liste___;
  GtkWidget *fixed10;
  GtkWidget *label76;
  GtkWidget *ayoub_verif_supprimer_button_non;
  GtkWidget *ayoub_verif_supprimer_button_oui;

  __tes_vous_sur_de_vouloir__supprimer_l_agent_de_la_liste___ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (__tes_vous_sur_de_vouloir__supprimer_l_agent_de_la_liste___), _("window9"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (__tes_vous_sur_de_vouloir__supprimer_l_agent_de_la_liste___), fixed10);

  label76 = gtk_label_new (_("\303\212tes-vous sur de vouloir  supprimer l'agent de la liste ? "));
  gtk_widget_show (label76);
  gtk_fixed_put (GTK_FIXED (fixed10), label76, 32, 16);
  gtk_widget_set_size_request (label76, 411, 95);

  ayoub_verif_supprimer_button_non = gtk_button_new_with_mnemonic (_("Non"));
  gtk_widget_show (ayoub_verif_supprimer_button_non);
  gtk_fixed_put (GTK_FIXED (fixed10), ayoub_verif_supprimer_button_non, 240, 112);
  gtk_widget_set_size_request (ayoub_verif_supprimer_button_non, 99, 59);

  ayoub_verif_supprimer_button_oui = gtk_button_new_with_mnemonic (_("Oui"));
  gtk_widget_show (ayoub_verif_supprimer_button_oui);
  gtk_fixed_put (GTK_FIXED (fixed10), ayoub_verif_supprimer_button_oui, 96, 112);
  gtk_widget_set_size_request (ayoub_verif_supprimer_button_oui, 99, 59);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (__tes_vous_sur_de_vouloir__supprimer_l_agent_de_la_liste___, __tes_vous_sur_de_vouloir__supprimer_l_agent_de_la_liste___, "__tes_vous_sur_de_vouloir__supprimer_l_agent_de_la_liste___");
  GLADE_HOOKUP_OBJECT (__tes_vous_sur_de_vouloir__supprimer_l_agent_de_la_liste___, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (__tes_vous_sur_de_vouloir__supprimer_l_agent_de_la_liste___, label76, "label76");
  GLADE_HOOKUP_OBJECT (__tes_vous_sur_de_vouloir__supprimer_l_agent_de_la_liste___, ayoub_verif_supprimer_button_non, "ayoub_verif_supprimer_button_non");
  GLADE_HOOKUP_OBJECT (__tes_vous_sur_de_vouloir__supprimer_l_agent_de_la_liste___, ayoub_verif_supprimer_button_oui, "ayoub_verif_supprimer_button_oui");

  return __tes_vous_sur_de_vouloir__supprimer_l_agent_de_la_liste___;
}

GtkWidget*
create_mot_de_passe_incorrecte (void)
{
  GtkWidget *mot_de_passe_incorrecte;
  GtkWidget *fixed11;
  GtkWidget *label77;
  GtkWidget *button23;

  mot_de_passe_incorrecte = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (mot_de_passe_incorrecte), _("window10"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (mot_de_passe_incorrecte), fixed11);

  label77 = gtk_label_new (_("          Impossible de continuer ! \nMot de passe saisi est incorrecte..."));
  gtk_widget_show (label77);
  gtk_fixed_put (GTK_FIXED (fixed11), label77, 16, 8);
  gtk_widget_set_size_request (label77, 554, 115);

  button23 = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (button23);
  gtk_fixed_put (GTK_FIXED (fixed11), button23, 240, 112);
  gtk_widget_set_size_request (button23, 100, 50);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mot_de_passe_incorrecte, mot_de_passe_incorrecte, "mot_de_passe_incorrecte");
  GLADE_HOOKUP_OBJECT (mot_de_passe_incorrecte, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (mot_de_passe_incorrecte, label77, "label77");
  GLADE_HOOKUP_OBJECT (mot_de_passe_incorrecte, button23, "button23");

  return mot_de_passe_incorrecte;
}

GtkWidget*
create_demande_mdp (void)
{
  GtkWidget *demande_mdp;
  GtkWidget *fixed12;
  GtkWidget *ayoub_demande_mdp_text_mdp_admin;
  GtkWidget *label78;
  GtkWidget *button24;
  GtkWidget *button26;

  demande_mdp = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (demande_mdp), _("window11"));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (demande_mdp), fixed12);

  ayoub_demande_mdp_text_mdp_admin = gtk_entry_new ();
  gtk_widget_show (ayoub_demande_mdp_text_mdp_admin);
  gtk_fixed_put (GTK_FIXED (fixed12), ayoub_demande_mdp_text_mdp_admin, 96, 97);
  gtk_widget_set_size_request (ayoub_demande_mdp_text_mdp_admin, 219, 44);
  gtk_entry_set_invisible_char (GTK_ENTRY (ayoub_demande_mdp_text_mdp_admin), 8226);

  label78 = gtk_label_new (_("Veuillez entrer votre mot de passe, s'il vous pla\303\256t..."));
  gtk_widget_show (label78);
  gtk_fixed_put (GTK_FIXED (fixed12), label78, 32, 45);
  gtk_widget_set_size_request (label78, 365, 46);

  button24 = gtk_button_new_with_mnemonic (_("Continuer"));
  gtk_widget_show (button24);
  gtk_fixed_put (GTK_FIXED (fixed12), button24, 152, 165);
  gtk_widget_set_size_request (button24, 100, 50);

  button26 = gtk_button_new_with_mnemonic (_("X"));
  gtk_widget_show (button26);
  gtk_fixed_put (GTK_FIXED (fixed12), button26, 416, 16);
  gtk_widget_set_size_request (button26, 40, 40);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (demande_mdp, demande_mdp, "demande_mdp");
  GLADE_HOOKUP_OBJECT (demande_mdp, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (demande_mdp, ayoub_demande_mdp_text_mdp_admin, "ayoub_demande_mdp_text_mdp_admin");
  GLADE_HOOKUP_OBJECT (demande_mdp, label78, "label78");
  GLADE_HOOKUP_OBJECT (demande_mdp, button24, "button24");
  GLADE_HOOKUP_OBJECT (demande_mdp, button26, "button26");

  return demande_mdp;
}

GtkWidget*
create_demande_modifier_cin_agent (void)
{
  GtkWidget *demande_modifier_cin_agent;
  GtkWidget *fixed13;
  GtkWidget *label80;
  GtkWidget *CIN;
  GtkWidget *button29;
  GtkWidget *label79;
  GtkWidget *output;
  GtkWidget *continuer;

  demande_modifier_cin_agent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (demande_modifier_cin_agent), _("window CIN agent \303\240 modifier"));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (demande_modifier_cin_agent), fixed13);

  label80 = gtk_label_new (_("CIN agent  : "));
  gtk_widget_show (label80);
  gtk_fixed_put (GTK_FIXED (fixed13), label80, 16, 70);
  gtk_widget_set_size_request (label80, 100, 40);
  gtk_misc_set_alignment (GTK_MISC (label80), 0, 0.5);

  CIN = gtk_entry_new ();
  gtk_widget_show (CIN);
  gtk_fixed_put (GTK_FIXED (fixed13), CIN, 160, 72);
  gtk_widget_set_size_request (CIN, 190, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (CIN), 8226);

  button29 = gtk_button_new_with_mnemonic (_("X"));
  gtk_widget_show (button29);
  gtk_fixed_put (GTK_FIXED (fixed13), button29, 368, 8);
  gtk_widget_set_size_request (button29, 40, 40);

  label79 = gtk_label_new (_("Mis \303\240 jour d'un compte agent de parking \n"));
  gtk_widget_show (label79);
  gtk_fixed_put (GTK_FIXED (fixed13), label79, 48, 16);
  gtk_widget_set_size_request (label79, 299, 41);

  output = gtk_label_new ("");
  gtk_widget_show (output);
  gtk_fixed_put (GTK_FIXED (fixed13), output, 24, 184);
  gtk_widget_set_size_request (output, 344, 41);

  continuer = gtk_button_new_with_mnemonic (_("continuer"));
  gtk_widget_show (continuer);
  gtk_fixed_put (GTK_FIXED (fixed13), continuer, 120, 128);
  gtk_widget_set_size_request (continuer, 130, 40);

  g_signal_connect ((gpointer) continuer, "clicked",
                    G_CALLBACK (on_ccontinuer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (demande_modifier_cin_agent, demande_modifier_cin_agent, "demande_modifier_cin_agent");
  GLADE_HOOKUP_OBJECT (demande_modifier_cin_agent, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (demande_modifier_cin_agent, label80, "label80");
  GLADE_HOOKUP_OBJECT (demande_modifier_cin_agent, CIN, "CIN");
  GLADE_HOOKUP_OBJECT (demande_modifier_cin_agent, button29, "button29");
  GLADE_HOOKUP_OBJECT (demande_modifier_cin_agent, label79, "label79");
  GLADE_HOOKUP_OBJECT (demande_modifier_cin_agent, output, "output");
  GLADE_HOOKUP_OBJECT (demande_modifier_cin_agent, continuer, "continuer");

  return demande_modifier_cin_agent;
}

GtkWidget*
create_date_de_r__servation (void)
{
  GtkWidget *date_de_r__servation;
  GtkWidget *fixed14;
  GtkWidget *button31;
  GtkObject *datedereservationjour_adj;
  GtkWidget *datedereservationjour;
  GtkObject *datedereservationannee_adj;
  GtkWidget *datedereservationannee;
  GtkWidget *label81;
  GtkWidget *output;
  GtkWidget *okreservation;
  GtkObject *datedereservationmois_adj;
  GtkWidget *datedereservationmois;

  date_de_r__servation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (date_de_r__servation), _("window Date de r\303\251servation"));

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (date_de_r__servation), fixed14);

  button31 = gtk_button_new_with_mnemonic (_("X"));
  gtk_widget_show (button31);
  gtk_fixed_put (GTK_FIXED (fixed14), button31, 336, 16);
  gtk_widget_set_size_request (button31, 40, 40);

  datedereservationjour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  datedereservationjour = gtk_spin_button_new (GTK_ADJUSTMENT (datedereservationjour_adj), 1, 0);
  gtk_widget_show (datedereservationjour);
  gtk_fixed_put (GTK_FIXED (fixed14), datedereservationjour, 37, 100);
  gtk_widget_set_size_request (datedereservationjour, 60, 27);

  datedereservationannee_adj = gtk_adjustment_new (1, 2000, 2024, 1, 10, 10);
  datedereservationannee = gtk_spin_button_new (GTK_ADJUSTMENT (datedereservationannee_adj), 1, 0);
  gtk_widget_show (datedereservationannee);
  gtk_fixed_put (GTK_FIXED (fixed14), datedereservationannee, 206, 100);
  gtk_widget_set_size_request (datedereservationannee, 92, 27);

  label81 = gtk_label_new (_("Entrer la date de la r\303\251servation : "));
  gtk_widget_show (label81);
  gtk_fixed_put (GTK_FIXED (fixed14), label81, 56, 40);
  gtk_widget_set_size_request (label81, 247, 40);

  output = gtk_label_new ("");
  gtk_widget_show (output);
  gtk_fixed_put (GTK_FIXED (fixed14), output, 24, 192);
  gtk_widget_set_size_request (output, 336, 33);

  okreservation = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (okreservation);
  gtk_fixed_put (GTK_FIXED (fixed14), okreservation, 120, 136);
  gtk_widget_set_size_request (okreservation, 88, 40);

  datedereservationmois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  datedereservationmois = gtk_spin_button_new (GTK_ADJUSTMENT (datedereservationmois_adj), 1, 0);
  gtk_widget_show (datedereservationmois);
  gtk_fixed_put (GTK_FIXED (fixed14), datedereservationmois, 120, 100);
  gtk_widget_set_size_request (datedereservationmois, 60, 27);

  g_signal_connect ((gpointer) okreservation, "clicked",
                    G_CALLBACK (on_okreservation_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (date_de_r__servation, date_de_r__servation, "date_de_r__servation");
  GLADE_HOOKUP_OBJECT (date_de_r__servation, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (date_de_r__servation, button31, "button31");
  GLADE_HOOKUP_OBJECT (date_de_r__servation, datedereservationjour, "datedereservationjour");
  GLADE_HOOKUP_OBJECT (date_de_r__servation, datedereservationannee, "datedereservationannee");
  GLADE_HOOKUP_OBJECT (date_de_r__servation, label81, "label81");
  GLADE_HOOKUP_OBJECT (date_de_r__servation, output, "output");
  GLADE_HOOKUP_OBJECT (date_de_r__servation, okreservation, "okreservation");
  GLADE_HOOKUP_OBJECT (date_de_r__servation, datedereservationmois, "datedereservationmois");

  return date_de_r__servation;
}

GtkWidget*
create_pas_de_r__servation (void)
{
  GtkWidget *pas_de_r__servation;
  GtkWidget *fixed15;
  GtkWidget *label82;
  GtkWidget *ayoub_pas_de_r__servation_button_OK;

  pas_de_r__servation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (pas_de_r__servation), _("window14"));

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (pas_de_r__servation), fixed15);

  label82 = gtk_label_new (_("D\303\251sol\303\251, aucune r\303\251servation n'est disponible \303\240 cette date..."));
  gtk_widget_show (label82);
  gtk_fixed_put (GTK_FIXED (fixed15), label82, 0, 40);
  gtk_widget_set_size_request (label82, 440, 63);

  ayoub_pas_de_r__servation_button_OK = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (ayoub_pas_de_r__servation_button_OK);
  gtk_fixed_put (GTK_FIXED (fixed15), ayoub_pas_de_r__servation_button_OK, 144, 96);
  gtk_widget_set_size_request (ayoub_pas_de_r__servation_button_OK, 128, 60);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (pas_de_r__servation, pas_de_r__servation, "pas_de_r__servation");
  GLADE_HOOKUP_OBJECT (pas_de_r__servation, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (pas_de_r__servation, label82, "label82");
  GLADE_HOOKUP_OBJECT (pas_de_r__servation, ayoub_pas_de_r__servation_button_OK, "ayoub_pas_de_r__servation_button_OK");

  return pas_de_r__servation;
}

GtkWidget*
create_liste_des_r__servations (void)
{
  GtkWidget *liste_des_r__servations;
  GtkWidget *fixed16;
  GtkWidget *treeview2;
  GtkWidget *label83;
  GtkWidget *output;

  liste_des_r__servations = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (liste_des_r__servations), _("window Liste des r\303\251servations"));
  gtk_window_set_default_size (GTK_WINDOW (liste_des_r__servations), 1300, 1000);

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (liste_des_r__servations), fixed16);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed16), treeview2, 24, 112);
  gtk_widget_set_size_request (treeview2, 519, 200);

  label83 = gtk_label_new (_("Date : "));
  gtk_widget_show (label83);
  gtk_fixed_put (GTK_FIXED (fixed16), label83, 16, 24);
  gtk_widget_set_size_request (label83, 80, 50);
  gtk_misc_set_alignment (GTK_MISC (label83), 0, 0.5);

  output = gtk_label_new ("");
  gtk_widget_show (output);
  gtk_fixed_put (GTK_FIXED (fixed16), output, 96, 32);
  gtk_widget_set_size_request (output, 280, 33);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (liste_des_r__servations, liste_des_r__servations, "liste_des_r__servations");
  GLADE_HOOKUP_OBJECT (liste_des_r__servations, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (liste_des_r__servations, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (liste_des_r__servations, label83, "label83");
  GLADE_HOOKUP_OBJECT (liste_des_r__servations, output, "output");

  return liste_des_r__servations;
}

GtkWidget*
create___tes_vous_sur_de_vouloir_modifier_les_information_de_l_agent (void)
{
  GtkWidget *__tes_vous_sur_de_vouloir_modifier_les_information_de_l_agent;
  GtkWidget *fixed24;
  GtkWidget *label107;
  GtkWidget *ayoub_verif_modifier_button_oui;
  GtkWidget *ayoub_verif_modifier_button_non;

  __tes_vous_sur_de_vouloir_modifier_les_information_de_l_agent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (__tes_vous_sur_de_vouloir_modifier_les_information_de_l_agent), _("window1"));

  fixed24 = gtk_fixed_new ();
  gtk_widget_show (fixed24);
  gtk_container_add (GTK_CONTAINER (__tes_vous_sur_de_vouloir_modifier_les_information_de_l_agent), fixed24);

  label107 = gtk_label_new (_("\303\212tes-vous sur de vouloir  modifier les donn\303\251s de l'agent ? "));
  gtk_widget_show (label107);
  gtk_fixed_put (GTK_FIXED (fixed24), label107, 8, 8);
  gtk_widget_set_size_request (label107, 411, 95);

  ayoub_verif_modifier_button_oui = gtk_button_new_with_mnemonic (_("Oui"));
  gtk_widget_show (ayoub_verif_modifier_button_oui);
  gtk_fixed_put (GTK_FIXED (fixed24), ayoub_verif_modifier_button_oui, 80, 88);
  gtk_widget_set_size_request (ayoub_verif_modifier_button_oui, 99, 59);

  ayoub_verif_modifier_button_non = gtk_button_new_with_mnemonic (_("Non"));
  gtk_widget_show (ayoub_verif_modifier_button_non);
  gtk_fixed_put (GTK_FIXED (fixed24), ayoub_verif_modifier_button_non, 224, 88);
  gtk_widget_set_size_request (ayoub_verif_modifier_button_non, 99, 59);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (__tes_vous_sur_de_vouloir_modifier_les_information_de_l_agent, __tes_vous_sur_de_vouloir_modifier_les_information_de_l_agent, "__tes_vous_sur_de_vouloir_modifier_les_information_de_l_agent");
  GLADE_HOOKUP_OBJECT (__tes_vous_sur_de_vouloir_modifier_les_information_de_l_agent, fixed24, "fixed24");
  GLADE_HOOKUP_OBJECT (__tes_vous_sur_de_vouloir_modifier_les_information_de_l_agent, label107, "label107");
  GLADE_HOOKUP_OBJECT (__tes_vous_sur_de_vouloir_modifier_les_information_de_l_agent, ayoub_verif_modifier_button_oui, "ayoub_verif_modifier_button_oui");
  GLADE_HOOKUP_OBJECT (__tes_vous_sur_de_vouloir_modifier_les_information_de_l_agent, ayoub_verif_modifier_button_non, "ayoub_verif_modifier_button_non");

  return __tes_vous_sur_de_vouloir_modifier_les_information_de_l_agent;
}

GtkWidget*
create_Veuillez_remplir_tous_les_champs (void)
{
  GtkWidget *Veuillez_remplir_tous_les_champs;
  GtkWidget *fixed25;
  GtkWidget *label108;
  GtkWidget *ayoub_verif_remplir_champs_button_OK;

  Veuillez_remplir_tous_les_champs = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Veuillez_remplir_tous_les_champs), _("window2"));

  fixed25 = gtk_fixed_new ();
  gtk_widget_show (fixed25);
  gtk_container_add (GTK_CONTAINER (Veuillez_remplir_tous_les_champs), fixed25);

  label108 = gtk_label_new (_("Veuillez remplir tous les champs requis !!"));
  gtk_widget_show (label108);
  gtk_fixed_put (GTK_FIXED (fixed25), label108, 24, 24);
  gtk_widget_set_size_request (label108, 328, 88);

  ayoub_verif_remplir_champs_button_OK = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (ayoub_verif_remplir_champs_button_OK);
  gtk_fixed_put (GTK_FIXED (fixed25), ayoub_verif_remplir_champs_button_OK, 128, 88);
  gtk_widget_set_size_request (ayoub_verif_remplir_champs_button_OK, 128, 60);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Veuillez_remplir_tous_les_champs, Veuillez_remplir_tous_les_champs, "Veuillez_remplir_tous_les_champs");
  GLADE_HOOKUP_OBJECT (Veuillez_remplir_tous_les_champs, fixed25, "fixed25");
  GLADE_HOOKUP_OBJECT (Veuillez_remplir_tous_les_champs, label108, "label108");
  GLADE_HOOKUP_OBJECT (Veuillez_remplir_tous_les_champs, ayoub_verif_remplir_champs_button_OK, "ayoub_verif_remplir_champs_button_OK");

  return Veuillez_remplir_tous_les_champs;
}

