/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Ajouter_un_agent (void);
GtkWidget* create_connexion_admin (void);
GtkWidget* create_Erreur_de_connexion_admin (void);
GtkWidget* create_Supprimer_un_agent (void);
GtkWidget* create_agent_introuvable (void);
GtkWidget* create_mis____jour_compte_agent (void);
GtkWidget* create_labelprincipale (void);
GtkWidget* create___tes_vous_sur_de_vouloir__supprimer_l_agent_de_la_liste___ (void);
GtkWidget* create_mot_de_passe_incorrecte (void);
GtkWidget* create_demande_mdp (void);
GtkWidget* create_demande_modifier_cin_agent (void);
GtkWidget* create_date_de_r__servation (void);
GtkWidget* create_pas_de_r__servation (void);
GtkWidget* create_liste_des_r__servations (void);
GtkWidget* create___tes_vous_sur_de_vouloir_modifier_les_information_de_l_agent (void);
GtkWidget* create_Veuillez_remplir_tous_les_champs (void);
