/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include "agent.h"

int
main (int argc, char *argv[])
{
    
    GtkWidget *Ajouter_un_agent;
    GtkWidget *connexion_admin;
    GtkWidget *Erreur_de_connexion_admin;
    GtkWidget *Supprimer_un_agent;
    GtkWidget *agent_introuvable;
    GtkWidget *mis____jour_compte_agent;
    GtkWidget *label_peincipale_Affichage_commande_;
    GtkWidget *__tes_vous_sur_de_vouloir__supprimer_l_agent_de_la_liste___;
    GtkWidget *mot_de_passe_incorrecte;
    GtkWidget *demande_mdp;
    GtkWidget *demande_modifier_cin_agent;
    GtkWidget *date_de_r__servation;
    GtkWidget *pas_de_r__servation;
    GtkWidget *liste_des_r__servations;
    GtkWidget *__tes_vous_sur_de_vouloir_modifier_les_information_de_l_agent;
    GtkWidget *Veuillez_remplir_tous_les_champs;
/*_____________________________________________________________________________*/
    GtkWidget *fenetre_lab_principale;
    GtkWidget *treeview1;
/*--------------------------------------------------------------------------------------------------------------*/

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
/*---------------------------------------------------------------------------------------------------------------*/
	
	fenetre_lab_principale=create_labelprincipale ();
	gtk_widget_show(fenetre_lab_principale);
	treeview1=lookup_widget(fenetre_lab_principale, "treeview1");
	afficher_agent(treeview1);

/*---------------------------------------------------------------------------------------------------------------*/
/*

  Ajouter_un_agent = create_Ajouter_un_agent ();
  gtk_widget_show (Ajouter_un_agent);

  connexion_admin = create_connexion_admin ();
  gtk_widget_show (connexion_admin);
  Erreur_de_connexion_admin = create_Erreur_de_connexion_admin ();
  gtk_widget_show (Erreur_de_connexion_admin);

  Supprimer_un_agent = create_Supprimer_un_agent ();
  gtk_widget_show (Supprimer_un_agent);*/
/*
  agent_introuvable = create_agent_introuvable ();
  gtk_widget_show (agent_introuvable);
  mis____jour_compte_agent = create_mis____jour_compte_agent ();
  gtk_widget_show (mis____jour_compte_agent);

  label_peincipale_Affichage_commande_ = create_labelprincipale ();
  gtk_widget_show (label_peincipale_Affichage_commande_);*/
/*
  __tes_vous_sur_de_vouloir__supprimer_l_agent_de_la_liste___ = create___tes_vous_sur_de_vouloir__supprimer_l_agent_de_la_liste___ ();
  gtk_widget_show (__tes_vous_sur_de_vouloir__supprimer_l_agent_de_la_liste___);
  mot_de_passe_incorrecte = create_mot_de_passe_incorrecte ();
  gtk_widget_show (mot_de_passe_incorrecte);
  demande_mdp = create_demande_mdp ();
  gtk_widget_show (demande_mdp);
  demande_modifier_cin_agent = create_demande_modifier_cin_agent ();
  gtk_widget_show (demande_modifier_cin_agent);

  date_de_r__servation = create_date_de_r__servation ();
  gtk_widget_show (date_de_r__servation);
  pas_de_r__servation = create_pas_de_r__servation ();
  gtk_widget_show (pas_de_r__servation);
  liste_des_r__servations = create_liste_des_r__servations ();
  gtk_widget_show (liste_des_r__servations);*/
/*
  __tes_vous_sur_de_vouloir_modifier_les_information_de_l_agent = create___tes_vous_sur_de_vouloir_modifier_les_information_de_l_agent ();
  gtk_widget_show (__tes_vous_sur_de_vouloir_modifier_les_information_de_l_agent);
  Veuillez_remplir_tous_les_champs = create_Veuillez_remplir_tous_les_champs ();
  gtk_widget_show (Veuillez_remplir_tous_les_champs);
*/
  gtk_main ();
  return 0;
}
